### ISSUE TITLE
Can't install CRAN packages during a training run

### ISSUE THREAD

**Issue by lucazav** [Azure/azureml-sdk-for-r#257] opened 2020-02-26 16:32 UTC
I'm executing an estimator to launch a training run. I'm declaring some CRAN packages to be installed in this way:

```
est <- estimator(source_directory = ".",
                 entry_script = "training_clustering.R",
                 cran_packages = c("tidyverse", "dtwclust", "clue"),
                 script_params = list("--data_folder" = ds$path(target_path)),
                 compute_target = compute_target
)
```

Looking at the _20_image_build_log.txt_ file, I'm getting the following error:

> > install.packages('dtwclust', repos = 'http://cran.us.r-project.org')
> [91mWarning: unable to access index for repository http://cran.us.r-project.org/src/contrib:
>   cannot open URL 'http://cran.us.r-project.org/src/contrib/PACKAGES'
> [0m[91mWarning message:
> package ‘dtwclust’ is not available (for R version 3.6.1) 
> [0m> 
> > 

The same error occurs for each declared package in _cran_packages_.
It seems that _http://cran.us.r-project.org_ is down. Is it possible to force another CRAN repo?
How can I fix it?

**Comment by revodavid** [comment] 2020-02-26 19:37
The issue is that the version of azuremlsdk on the Compute Instances in Azure ML service are out of date. You can work around the issue in the meantime by running:

```
install.packages("azuremlsdk") 
```

in RStudio on the Compute Instance to install the latest version on CRAN. You can check you have the latest version as follows:

```
> packageVersion("azuremlsdk")
[1] ‘0.6.85’
```

**Comment by sdonohoo** [comment] 2020-02-26 19:44
I also follow up the `install.packages("azuremlsdk")` update with:

`> azuremlsdk::install_azureml(version = '1.0.85', remove_existing_env = TRUE)`

to refresh the underlying python env.

**Comment by mx-iao** [comment] 2020-03-02 19:38
FYI here is the troubleshooting guide section for updating R SDK on Compute instance: https://azure.github.io/azureml-sdk-for-r/articles/guides/troubleshooting.html#compute-instance

**Comment by mx-iao** [comment] 2020-04-08 21:27
Closing now as new compute instances provisioned have v0.6.85 installed by default.

**Closed by mx-iao** 2020-04-08 21:27 UTC
