### ISSUE TITLE
 load_dataset_into_data_frame from Azure SQL Database is extremely slow

### ISSUE THREAD

**Issue by lucazav** [Azure/azureml-sdk-for-r#314] opened 2020-04-10 08:43 UTC
I'm fetching data from my Azure SQL Database (3mln rows) in the following way from the Compute Instance:

```
dp <- data_path( sql_ds, sqlQuery )
tds <- create_tabular_dataset_from_sql_query(dp)
df <- load_dataset_into_data_frame(tds)
```

The process is really slow and makes RStudio continuously popup the following error:

![image](https://user-images.githubusercontent.com/6104437/78976816-40368300-7b17-11ea-9ed0-edaae5324dc0.png)

I also tried to run the same code in my on-prem RStudio. I've installed the latest R and Python SDK. When executing the `create_tabular_dataset_from_sql_query()` function I get this error:

> Error in py_call_impl(callable, dots$args, dots$keywords) : 
>   OSError: [WinError 6] The handle is invalid 
> 3
> stop(structure(list(message = "OSError: [WinError 6] The handle is invalid", 
>     call = py_call_impl(callable, dots$args, dots$keywords), 
>     cppstack = NULL), class = c("Rcpp::exception", "C++Error", 
> "error", "condition"))) 
> 2
> azureml$core$dataset$Dataset$Tabular$from_sql_query(query = query, 
>     validate = validate, set_column_types = set_column_types, 
>     query_timeout = as.integer(query_timeout)) 
> 1
> create_tabular_dataset_from_sql_query(dp)

**Comment by diondrapeck** [comment] 2020-04-10 15:34
Hi Luca, I will close this issue since it's a duplicate of your issue in #256. That issue is still open and under investigation. When there's an update, it will be communicated there.

**Closed by diondrapeck** 2020-04-10 15:34 UTC
