### ISSUE TITLE
AzureML Widget fails to display run details

### ISSUE THREAD

**Issue by revodavid** [Azure/azureml-sdk-for-r#318] opened 2020-04-14 23:12 UTC
**Describe the bug**
In RStudio `view_run_details` is meant to display a widget with run information, but this fails in an AML Compute instance with azuremlsdk 0.6.85 installed

**To Reproduce**
* Create a new Azure ML Compute Instance
* Launch RStudio
* Run the vignette "Train and deploy your first model with Azure ML" through the command `view_run_details(run)`
* See this in the viewer pane:

![image](https://user-images.githubusercontent.com/152948/79282687-a6e6d400-7e6a-11ea-86f2-a9718492767b.png)

**Expected behavior**
Run details with a link to the studio page for the run shown in the Viewer pane

**Screenshots**
See above

**Comment by mx-iao** [comment] 2020-04-15 03:54
@diondrapeck is this a duplicate of #292?

**Comment by revodavid** [comment] 2020-04-16 00:16
This above screenshot was taken in RStudio Server running in the Compute Instance. 

I just tried it from a local instance of RStudio and the widget appears momentarily but then this error appears after you click "Link" in the widget. The correct page in Azure ML studio does get displayed however.
```
[1] "Listening on 127.0.0.1:5054"
Warning: Error in py_call_impl: AttributeError: 'str' object has no attribute '_get_service_client'

Detailed traceback: 
  File "C:\Users\davidsmi\AppData\Local\Continuum\anaconda3\envs\r-reticulate\lib\site-packages\azureml\core\workspace.py", line 451, in get
    result_dict = Workspace.list(subscription_id, auth=auth, resource_group=resource_group)
  File "C:\Users\davidsmi\AppData\Local\Continuum\anaconda3\envs\r-reticulate\lib\site-packages\azureml\core\workspace.py", line 510, in list
    workspaces_list = Workspace._list_legacy(auth, subscription_id=subscription_id)
  File "C:\Users\davidsmi\AppData\Local\Continuum\anaconda3\envs\r-reticulate\lib\site-packages\azureml\core\workspace.py", line 997, in _list_legacy
    raise e
  File "C:\Users\davidsmi\AppData\Local\Continuum\anaconda3\envs\r-reticulate\lib\site-packages\azureml\core\workspace.py", line 991, in _list_legacy
    resource_group_name=resource_group_name)
  File "C:\Users\davidsmi\AppData\Local\Continuum\anaconda3\envs\r-reti [... truncated]
  89: <Anonymous>
```

**Comment by revodavid** [comment] 2020-04-16 00:29
Same error appears if you just wait 10 seconds, no need to click the link

**Comment by diondrapeck** [comment] 2020-04-22 22:03
@mx-iao yes

**Closed** 2020-04-27 15:41 UTC
Labels: bug, in-progress
