### ISSUE TITLE
No non-system installation of Python could be found

### ISSUE THREAD

**Issue by revodavid** [Azure/azureml-sdk-for-r#317] opened 2020-04-14 22:50 UTC
**Describe the bug**
Loading the azuremlsdk package with `library(azuremlsdk)` generates an error and prompt:

```
No non-system installation of Python could be found. Would you like to download and install Miniconda? Miniconda is an open source environment management system for Python. See https://docs.conda.io/en/latest/miniconda.html for more details.
 
Would you like to install Miniconda? [Y/n]: 
```

**To Reproduce**
* Create a fresh Azure ML Compute Instance and launch RStudio using the link in Azure ML studio.
* At the R console, type `library(azuremlsdk)`

**Expected behavior**
`library(azuremlsdk)` generates no output or prompt, and the package loads

**Screenshots**
![image](https://user-images.githubusercontent.com/152948/79281045-da276400-7e66-11ea-9b09-906fa83555f2.png)

**Additional context**
Choosing `n` to the prompt gives the message `Installation aborted.` but the package loads successfully. After this, new RStudio sessions do not generate the error or prompt when loading the package.

The prompt itself causes scripts and vignettes loading the library to block.

```
> installed.packages()["azuremlsdk","Version"]
[1] "0.6.85"
```

**Comment by mx-iao** [comment] 2020-04-15 00:06
@revodavid This is a design decision from the reticulate package: https://github.com/rstudio/reticulate/issues/607

You will need to respond "n" to the prompt, and you should only be prompted once for that machine.

**Comment by revodavid** [comment] 2020-04-15 00:18
In this case, the azuremlsdk user isn't installing reticulate directly, and Python azureml installs its own Anaconda distro. So this prompt is a surprise to the user (and it still blocks scripts). Perhaps we can suppress it somehow?

**Comment by mx-iao** [comment] 2020-04-15 03:58
Yeah, we will look into seeing if we can disable/suppress the prompt on the compute instance. https://github.com/rstudio/reticulate/issues/710 looks like something we can look into. @diondrapeck FYI

**Comment by mx-iao** [comment] 2020-07-23 23:15
Dupe of #361

**Closed by mx-iao** 2020-07-23 23:15 UTC
Labels: mitigated
