### ISSUE TITLE
Can't zip files into the "outputs" folder

### ISSUE THREAD

**Issue by lucazav** [Azure/azureml-sdk-for-r#306] opened 2020-04-01 17:44 UTC
I'm trying to create a zip file of all the RDS files I saved into the `outputs` folder in this way:

```
saveRDS(object1, file = "./outputs/object1.rds")
saveRDS(object2, file = "./outputs/object2.rds")
...
saveRDS(object9, file = "./outputs/object9.rds")

#########################################
##  Zip all the RDS fils into model.zip
#########################################

if (file.exists("./outputs/model.zip")){
  file.remove("./outputs/model.zip")
}

rds_files <- list.files(path='./outputs', pattern="*.rds", full.names = TRUE)

zip("./outputs/model.zip", rds_files)
```

After the run is completed, I can't find the zip file into the `outputs` folder.
Am I missing something?

**Comment by revodavid** [comment] 2020-04-16 16:49
This is just a guess, but if you're running in a training cluster those are Linux VMs, and the "zip" command might not exist there. Do you see any errors in the log file? An error would appear in 70_driver_log.txt, which you can find in the Runs section in ml.azure.com

![image](https://user-images.githubusercontent.com/152948/79483724-7ec0b780-7fc7-11ea-8d28-a418f09330bc.png)

**Comment by lucazav** [comment] 2020-04-16 17:21
Hi @revodavid,

no errors. The run ends with the state of "Completed".
In the meanwhile I gave up on the idea of using a zip file, I've just registered a model declaring the folder containing all the files I need.
By the way, the [zip package](https://cran.r-project.org/web/packages/zip/zip.pdf) is cross-platform.

**Comment by mx-iao** [comment] 2020-04-27 20:38
@lucazav I don't think the issue is with Azure ML. You need to make sure that the zip package dependency is captured in your environment, and then you need to load in the package in the training script: `library(zip)`. If the package doesn't get loaded, then the `zip()` call doesn't do anything (I tried this locally). Also, it looks like `zip::zip()` is deprecated so I would switch to `zip::zipr()` instead.

**Comment by lucazav** [comment] 2020-04-27 20:47
Thank you @mx-iao, I'll try what you suggested

**Comment by mx-iao** [comment] 2020-05-20 20:26
Closing, please reopen if needed.

**Closed by mx-iao** 2020-05-20 20:26 UTC
